### ISSUE TITLE
can't touch "done"

### ISSUE THREAD

**Issue by nutpantz** [newhinton/disky#1]
It's below the navigation bar
Pixel6 A12
Fdroid 1.02

![Screenshot_20240413-202433](https://github.com/newhinton/disky/assets/12160507/23186e22-e126-4552-a1d9-45fbdaa4882e)

**Comment by newhinton** [comment]
@nutpantz Thanks for reporting this! I have fixed the issue with a new release. However, my testing showed that it is still possible to touch the done button, it is just quite hard to do so. Another workaround would be to temporarily switch to gesture-navigation, which uses a way smaller bottom bar. That will allow you to touch done.

**Comment by uli-on** [comment]
Much simpler, as a - I hope temporary - workaround: turn the device to landscape.
