### ISSUE TITLE
Settings gearwheel

### ISSUE THREAD

**Issue by erdnuesse** [newhinton/disky#18]
Don't use a settings symbol for a donation message. 
Bad UI, bad practice. It's not a shame to ask for donations, but not like that. 

This makes it seem like, there's either a bug - or more settings available after donating. 

If it's neither, it should be changed.

**Comment by newhinton** [comment]
Closed by 84a5679d6ff8988aa968455ea049b95a4626d205
That one implements the planned sorting option.

Also, i don't think it's that big of a deal. But now there are settings! :D
