### ISSUE TITLE
How do you treat other users' apps?

### ISSUE THREAD

**Issue by volker001** [newhinton/disky#19]
They take up storage space but are not visible to the current user...

**Comment by newhinton** [comment]
I currently do not handle other users/profiles at all. Though i did not specifically looked at possible api's, i do not think they would be accessible to other users.

Generally, everything that is not apps, or a file in the internal storage, will be counted towards the operating system. This is also why it's size fluctuates.

I have planned to include this information in the app itself in a future update.

**Comment by newhinton** [comment]
Closed by 6eda1c5537ab8cf86ea2b8a51ce322a2f5fe52ad
I added an in-app faq wich explains this.
