### ISSUE TITLE
App hangs at varying percentages unless cache is cleared.

### ISSUE THREAD

**Issue by PiplupTrainer** [newhinton/disky#29]
Steps to re-produce:
Open app
Use app for a period of time
Try to re-open the app or rescan in app

Behavior:
App will hang when scanning at a varying percentage

Steps to manually fix:
Clear cache or app data

I am running the latest build of the app on Android 14. My phone is a Google Pixel 8 running the latest version.

**Comment by newhinton** [comment]
Duplicate of #28.
